version: "3.4"
services:
    api:
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "8080:80"
          - "443:44380"
        depends_on:
          - db
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Tran5f3rMat3"
            ACCEPT_EULA: "Y"